### ISSUE TITLE
Spin up a Geth client for Mainnet and consider using it as a default mainnet client

### ISSUE THREAD

**Issue by alex-murashkin** [quantstamp/eth-router#38]
To achieve a better parity between development (Rospten) and production (Mainnet), we should consider spinning up a Go-Ethereum node connected to the Mainnet and use it as a default client for the `/mainnet` route.

**Comment by Matt-Holland** [comment]
@alex-murashkin I'd like to propose re-stating this as: "To achieve a better parity between (Rospten) and production (Mainnet), we should consider using the same client software on both networks, rather than one type of client on Ropsten and a different type of client on Mainnet."

My reason is, to separate the question of "should we use the same client software in all cases" from the question of "should the client software be Geth or Parity". Then we can address each question fully but separately.

Agree?

**Comment by alex-murashkin** [comment]
@Matt-Holland I am not sure it makes a difference in the end, but sure - if it's convenient, let's separate the two.

**Comment by alex-murashkin** [comment]
Yes - Kyle has set this up on Friday. Both clients are of the same Geth version.

**Comment by lazzarello** [comment]
Notably, geth has significantly higher resource requirements than parity. A single mainnet node needs between 16GB and 32GB of RAM.

**Comment by kdunn926** [comment]
Looks like we can close this issue for now. 👏

**Comment by lazzarello** [comment]
wait, no the code should change to make a geth mainnet node the default. I don't think any changes were merged to do this.

**Comment by lazzarello** [comment]
closed with #52
